### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'name'

### ISSUE THREAD

**Issue by carmenchui** [thahmann/macleod#40]
The following error gets thrown for some CLIF files with imports:

`2020-03-25 23:30:54,626 macleod.Commands               DEBUG    CONSTRUCTING COMMAND FOR: prover9 FROM /Users/cchui/Documents/GitHub/colore/ontologies/kinship/kinship.clif
2020-03-25 23:30:54,626 bin.clif_converter             INFO     Converting /Users/cchui/Documents/GitHub/colore/ontologies/kinship/kinship.clif to ladr format
Traceback (most recent call last):
  File "macleod/gui/gui_beta/gui_main.py", line 299, in check_consistency_command
    (return_value, fastest_reasoner) = ontology.check_consistency(resolve=True)
  File "/Users/cchui/Documents/GitHub/macleod/macleod/Ontology.py", line 217, in check_consistency
    reasoners.constructAllCommands(self)
  File "/Users/cchui/Documents/GitHub/macleod/macleod/ReasonerSet.py", line 38, in constructAllCommands
    r.constructCommand(ontology)
  File "/Users/cchui/Documents/GitHub/macleod/macleod/Reasoner.py", line 65, in constructCommand
    self.args = commands.get_system_command(self.name, ontology)
  File "/Users/cchui/Documents/GitHub/macleod/macleod/Commands.py", line 26, in get_system_command
    return handlers.get(system_name, get_empty_cmd)(ontology)
  File "/Users/cchui/Documents/GitHub/macleod/macleod/Commands.py", line 39, in get_p9_cmd
    args.append(clif_converter.convert_single_clif_file(ontology,clif_converter.ladr_output,True))
  File "/Users/cchui/Documents/GitHub/macleod/bin/clif_converter.py", line 32, in convert_single_clif_file
    results = ontology.to_ladr(resolve)
  File "/Users/cchui/Documents/GitHub/macleod/macleod/Ontology.py", line 194, in to_ladr
    all_modules = self.get_all_modules()
  File "/Users/cchui/Documents/GitHub/macleod/macleod/Ontology.py", line 131, in get_all_modules
    print ("Found import " + onto.name)
AttributeError: 'NoneType' object has no attribute 'name'
Abort trap: 6
`
What happens:
- Python3 crashes
- GUI closes automatically

Test file:
- http://colore.oor.net/kinship/kinship.clif

I've checked the imports and the CLIF files themselves look fine and don't appear to have any syntax errors.  It seems like the imported CLIF files don't get initialized with the 'name' attribute when it gets parsed by Macleod.

Any thoughts on what might be causing this?

**Comment by thahmann** [comment]
the GUI is currently not functional at all - it still calls all the old methods. Not sure when that can be fixed. But the command line scrips (e.g. check_consistency or parse_clif) are working now more robustly.

**Comment by carmenchui** [comment]
@thahmann Ok, noted. I'll close this issue then.
